### ISSUE TITLE
Problem when subscriber_example's topicCallback() used in a method

### ISSUE THREAD

**Issue by teshanshanuka** [facontidavide/type_introspection_tests#1]
I am fairly new to the features of C++11. I tried your example and it works fine as it is. However when I put the `topicCallback()` in a Class, it's instances appear to share its global variables - public or private.
```
class Foo{
private:
    std::string _topic;
public:
    Foo(std::map <std::string, std::string>& info)
    {
        _topic = info["topic"];
    };
    void topicCallback(const topic_tools::ShapeShifter::ConstPtr& msg,
                   const std::string &topic_name,
                   RosIntrospection::Parser& parser)
    {
        ---EXAMPLE CODE---
        cout << _topic << endl;
    }
}

main(){
    ---SOME CODE---
    for (auto &info : topics)
    {
        Foo f(info);
        boost::function<void(const topic_tools::ShapeShifter::ConstPtr&) > callback;
        callback = [&parser, &info, &f](const topic_tools::ShapeShifter::ConstPtr& msg) -> void
        {
            f.topicCallback(msg, info.at("topic"), parser) ;
        };
        subscribers.push_back( nh.subscribe(info["topic"], 10, callback) );
    }
    ---SOME MORE CODE---
}
```
When I create several instances of the class and subscribe to the callback just as in the example code, `_topic` appears to be the same for all instances. Actually it is the topic of the last instance I create. What am I doing wrong?

**Comment by facontidavide** [comment]
This is correct. If you want a different instance for each topic, you must not share the single object f among all the subscribers. This is not related to my library, is how c++ works
