### ISSUE TITLE
accessing blob data

### ISSUE THREAD

**Issue by sthoduka** [facontidavide/type_introspection_tests#2]
Hello,
is it possible to access the name and data of fields which contain blob data?
From the rosbag example, it appears that the blob fields are not retrievable.
I tried with nav_msgs/OccupancyGrid and get the following output:

```
--------- /map ----------
 /map/header/seq = 0.000000
 /map/header/stamp = 1511449450.427709
 /map/info/map_load_time = 1511449450.427709
 /map/info/resolution = 0.020000
 /map/info/width = 2080.000000
 /map/info/height = 992.000000
 /map/info/origin/position/x = -16.520000
 /map/info/origin/position/y = -5.000000
 /map/info/origin/position/z = 0.000000
 /map/info/origin/orientation/x = 0.000000
 /map/info/origin/orientation/y = 0.000000
 /map/info/origin/orientation/z = 0.000000
 /map/info/origin/orientation/w = 1.000000
 /map/header/frame_id = map
```

The `/map/data` field is missing. 

I do see that blob data is treated differently [here](https://github.com/facontidavide/ros_type_introspection/blob/master/src/ros_introspection.cpp#L394). Do you have an examples where you access blob data?
thanks!

**Comment by facontidavide** [comment]
You can find the blobs here:

https://github.com/facontidavide/ros_type_introspection/blob/master/include/ros_type_introspection/ros_introspection.hpp#L61

The main limitation right now is that the field name of blobs can not be renamed using `Parser::applyNameTransform`, which works only for `FlatMessage::value`.

**Comment by sthoduka** [comment]
Yes, I can access the blob but didn't realize it was limited to `uint8` arrays. So, for example, I'm able to access the blob related to `data` from [PointCloud2](http://docs.ros.org/melodic/api/sensor_msgs/html/msg/PointCloud2.html), but not, the array `data` from [OccupancyGrid](http://docs.ros.org/melodic/api/nav_msgs/html/msg/OccupancyGrid.html), nor `ranges` from [LaserScan](http://docs.ros.org/melodic/api/sensor_msgs/html/msg/LaserScan.html).

However, I now see the comment about the usage of `deserializeIntoFlatContainer` for messages with large arrays (i.e. that it's not recommended), so I will see it I can solve it some other way.
thanks for the help!

**Comment by facontidavide** [comment]
Indeed. There is no easy solution to this problem.
There is easy way to decide in advance if a vector should be split in single values (like JointStates) or if it should be stored as a blob.

The heuristics I used (large vectors of `uint8_t`) was in fact based on Images, Maps and PointClouds.

There might be ways to refactor the code and deal with more use cases, but right now it is not my priority to deal with this limitation.

Feel free to fork the project and modify it ;)
